DROP TABLE IF EXISTS USER_INFO;
DROP TABLE IF EXISTS USER_PHONE;

DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USUARIOS_ROLES;

CREATE TABLE  USER_INFO (
    USR_ID BINARY(16) PRIMARY KEY,
    USR_NAME VARCHAR(255) NOT NULL,
    USR_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USR_PASSWORD VARCHAR(255) NOT NULL,
    USR_CREATED TIMESTAMP,
    USR_MODIFIED TIMESTAMP,
    USR_LAST_LOGIN TIMESTAMP,
    USR_TOKEN VARCHAR(255),
    USR_ACTIVE BOOLEAN,
    USR_STATUS VARCHAR(255)
);

CREATE TABLE USER_PHONE (
    PHO_ID BINARY(16) PRIMARY KEY,
    PHO_NUMBER VARCHAR(255) NOT NULL UNIQUE,
    PHO_CITY VARCHAR(255) NOT NULL,
    PHO_COUNTRY VARCHAR(255) NOT NULL,
    USR_ID BINARY(16),
    FOREIGN KEY (USR_ID) REFERENCES USER_INFO(USR_ID)
);

CREATE TABLE  ROLE (
    ID_ROLE BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE  USUARIO (
    ID_USUARIO BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CONSTRAINT UK_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE  USUARIOS_ROLES (
    USUARIO_ID BIGINT,
    ROLE_ID BIGINT,
    PRIMARY KEY (USUARIO_ID, ROLE_ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID_ROLE)
);
