DROP TABLE IF EXISTS USER_TABLE;

create table USER_TABLE (
	USER_NAME VARCHAR(20) primary key,
	USER_LASTNAME VARCHAR(20)
);

insert into	USER_TABLE (USER_NAME, USER_LASTNAME)
values 	
	('USER1', 'LASTNAME1'),
	('USER2', 'LASTNAME2');
